/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_ed25519verifyingkey_free: (a: number, b: number) => void;
export const ed25519verifyingkey_from_bytes: (a: number) => [number, number, number];
export const ed25519verifyingkey_is_weak: (a: number) => number;
export const ed25519verifyingkey_to_bytes: (a: number) => number;
export const ed25519verifyingkey_verify: (a: number, b: number, c: number) => number;
export const ed25519verifyingkey_verify_strict: (a: number, b: number, c: number) => number;
export const ed25519verifyingkey_new: (a: number) => [number, number, number];
export const __wbg_ed25519signature_free: (a: number, b: number) => void;
export const ed25519signature_from_bytes: (a: number) => [number, number, number];
export const ed25519signature_to_bytes: (a: number) => number;
export const ed25519signature_r_bytes: (a: number) => number;
export const ed25519signature_s_bytes: (a: number) => number;
export const ed25519signature_new: (a: number) => [number, number, number];
export const __wbg_ed25519signingkey_free: (a: number, b: number) => void;
export const ed25519signingkey_new: () => number;
export const ed25519signingkey_from_bytes: (a: number) => [number, number, number];
export const ed25519signingkey_from_keypair_bytes: (a: number) => [number, number, number];
export const ed25519signingkey_to_bytes: (a: number) => number;
export const ed25519signingkey_to_keypair_bytes: (a: number) => number;
export const ed25519signingkey_verifying_key: (a: number) => number;
export const ed25519signingkey_sign: (a: number, b: number) => number;
export const ed25519signingkey_verify: (a: number, b: number, c: number) => number;
export const ed25519signingkey_verify_strict: (a: number, b: number, c: number) => number;
export const ed25519signingkey_random: () => number;
export const __wbg_memory_free: (a: number, b: number) => void;
export const memory_new: (a: number, b: number) => number;
export const memory_ptr: (a: number) => number;
export const memory_len: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
